### ISSUE TITLE
Mat Drawer Pushes App Bar off the screen.

### ISSUE THREAD

**Issue by groogiam** [SamProf/MatBlazor#697]
**Describe the bug**
When using the MatDrawer with the MatAppBar opening the drawer pushes the contents of the app bar off the screen rather than resizing them. 

**To Reproduce**
See Blazor Fiddle Link
Clicking the menu opens the drawer but pushes the title and heart symbol of the screen.

**Blazorfiddle link**
https://blazorfiddle.com/s/pbg0fm6r

**Expected behavior**
App Bar should container should be made smaller condensing the content rather than moving it off the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/1992395/91524667-c76d7300-e8cd-11ea-9301-1fb85817944d.png)

![image](https://user-images.githubusercontent.com/1992395/91524646-bb81b100-e8cd-11ea-911d-c5eaaebef1ac.png)

**Comment by Raysapps** [comment]
I've noticed the same issue. The login button at the end of the MatAppBar moved out of the screen. Any suggested workaround?

**Comment by groogiam** [comment]
This css seems to help but I have not thoroughly tested it. However it would be nice if there was some way to handle this as a setting.

```css
/* condense app bar rather than push it off the screen */

.mdc-top-app-bar {
    z-index: 7 !important;
    position: sticky !important;
}
```
